@Ch11_App.Server_HostAddress = https://localhost:7151

# @name auth
POST {{Ch11_App.Server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET {{Ch11_App.Server_HostAddress}}/weatherforecast
Authorization: Bearer {{auth.response.body.$.token}}


