@ClaimsDashboard.Server_HostAddress = https://localhost:7122

GET {{ClaimsDashboard.Server_HostAddress}}/weatherforecast

###

POST {{ClaimsDashboard.Server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "password"
}

###

# @name auth
POST {{ClaimsDashboard.Server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET {{ClaimsDashboard.Server_HostAddress}}/weatherforecast
Authorization: Bearer {{auth.response.body.$.token}}

